### ISSUE TITLE
Tenant password reset token is being stored on landlord password_reset_tokens table

### ISSUE THREAD

**Issue by herecomeslucky0145** [spatie/laravel-multitenancy#483] opened 2023-08-13 04:48 UTC
I am using filamentphp v3 with AdminPanel and TenantPanel, At the end of configuring and testing password resets I noticed that :  for the password reset tokens the `password reset` requested from tenant panel is being stored to landlord database, while the reset works just fine. I wonder what is causing this behavior ! , Everything works fine despite the tenant password resets being stored on landlord's table.
The password reset mail just works with the tenant subdomain and the password reset is successful but I find this behavior weird.
I need some guidance.

I am using different password brokers for landlord and tenant : 

```
 'providers' => [
        'landlords' => [
            'driver' => 'eloquent',
            'model' => App\Models\Landlord\User::class,
        ],

        'tenants' => [
            'driver' => 'eloquent',
            'model' => App\Models\Tenant\User::class,
        ],
    ], 
'passwords' => [
        'landlords' => [
            'provider' => 'landlords',
            'table' => 'password_reset_tokens',
            'expire' => 60,
            'throttle' => 60,
        ],
        'tenants' => [
            'provider' => 'tenants',
            'table' => 'password_reset_tokens',
            'expire' => 60,
            'throttle' => 60,
        ],
    ],

```
landlord password resets works too. Everything is working as expected.

**Comment by masterix21** [comment] 2023-08-22 14:09
Duplicate of https://github.com/spatie/laravel-multitenancy/discussions/482

**Closed by masterix21** 2023-08-22 14:09 UTC
