### ISSUE TITLE
Queue retry fails for tenant aware jobs

### ISSUE THREAD

**Issue by aginev** [spatie/laravel-multitenancy#259] opened 2021-06-15 14:00 UTC
Hello, 

Forgive me if I'm wrong, but I think that there is an issue when trying to retry failed tenant aware jobs.

- configuration `queues_are_tenant_aware_by_default` set to `true`
- Not trying to add the jobs into the tenant databases (most of issues are related to this)

1. Typical failed job retry

`php artisan queue:retry ID` fails because it can not unserialize the payload command at [\Illuminate\Queue\Console\RetryCommand::refreshRetryUntil](https://github.com/laravel/framework/blob/ea695bf5974c90347264efdb5f724562846cbe62/src/Illuminate/Queue/Console/RetryCommand.php#L156-L183). Switch tenant database never called...

2. Retry job via tenant aware command - **NO** tenant specified

`php artisan tenants:artisan "queue:retry ID"` partially works but it's executed for every tenant which means that command will succeed only once and will fail for all other tenants. 

3. Retry job via tenant aware command - tenant specified

`php artisan tenants:artisan "queue:retry ID" --tenant=TENANT_ID` works as it should but this means that every time we should check for the `TENANT_ID` at the payload which is nasty ;). When you have a lot jobs failed it's even worse...

Possible solution could be if we have tenant aware queue retry command that could extend `\Illuminate\Queue\Console\RetryCommand` and wrap `retryJob` parents method with set/forget tenant calls if it's a tenant aware job of course.

What do you think about this solution? Any better ideas?

**Comment by James4645** [comment] 2021-06-15 15:24
Is your failed jobs migration part of your tenant migrations or tour landlords migrations? It almost sounds like it might be in your tenant migrations. I know I almost forgot to move mine to the landlord migrations folder.

**Comment by aginev** [comment] 2021-06-15 15:47
@James4645 jobs and failed_jobs tables are at landlord database. No such tables at tenant databases.

**Comment by masterix21** [comment] 2021-06-16 09:29
Hi @aginev, sorry, I tried, and works. Can you create a repository on GitHub with an example code? Thanks

**Comment by aginev** [comment] 2021-06-16 12:50
@masterix21 

It's just a fresh Laravel installation with multi tenancy package added.

https://github.com/aginev/spatie-laravel-multitenancy-test

Note:
1. [App\Multitenancy\Tasks\SwitchTenantDatabaseTask](https://github.com/aginev/spatie-laravel-multitenancy-test/blob/master/app/Multitenancy/Tasks/SwitchTenantDatabaseTask.php) is used when switching tenants because extra database configuration is required. For the sake of the damo all additions are disabled.
2. Tenant model has been extended as well just because extra database configuration
3. Most the actions are handled at [routes/web.php](https://github.com/aginev/spatie-laravel-multitenancy-test/blob/master/routes/web.php) just for simplicity reasons

Domain tenant finder has been used. This will require to add some hosts at `/etc/hosts`

```
127.0.0.1       admin.multitenancy.test
127.0.0.1       t1.multitenancy.test
127.0.0.1       t2.multitenancy.test
```

Example Nginx config
```
server {
	listen 80;
	listen [::]:80;

	root /home/aginev/Work/playground/multitenancy/public;

	index index.php;

	server_name admin.multitenancy.test t1.multitenancy.test t2.multitenancy.test;

	location / {
		try_files $uri $uri/ /index.php?$query_string;
	}

	# pass PHP scripts to FastCGI server
	location ~ \.php$ {
		include snippets/fastcgi-php.conf;
		fastcgi_pass unix:/var/run/php/php8.0-fpm.sock;
	}

	# deny access to .htaccess files, if Apache's document root
	# concurs with nginx's one
	location ~ /\.ht {
		deny all;
	}
}
```

Laravel's .env (just the changes from defaults)
```
...
APP_URL=http://multitenancy.test
...
DB_CONNECTION=landlord
...
DB_DATABASE=multitenancy
...
```

You will need 3 databases (1 landlord and 2 for the tenants) named:
```
multitenancy
multitenancy-1
multitenancy-2
```

Run the landlord migrations:
`php artisan migrate:fresh --database=landlord --path=database/migrations/landlord`

Visit [http://admin.multitenancy.test/](http://admin.multitenancy.test/) and click at the `Add Tenant` button. A new tenant will be created. Note that 3th click at the button will result a error because the example configuration is made just for 2 tenants. Tenant database will be migrated and 10 dummy users will be added (commands [here](https://github.com/aginev/spatie-laravel-multitenancy-test/tree/master/app/Actions)).

Visit [http://t1.multitenancy.test/](http://t1.multitenancy.test/). Queued job for random user will be despatched.

Run `php artisan queue:work --queue=users --once` and will get job failed.

Run `php artisan queue:retry all` and will get `SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected`

To be sure that the [SwitchTenantDatabaseTask::makeCurrent](https://github.com/aginev/spatie-laravel-multitenancy-test/blob/33b9e19dea0f4060961e53148a8be00be53c26f8/app/Multitenancy/Tasks/SwitchTenantDatabaseTask.php#L15) has been never called. Added `dd()` statement in there and nothing (of course tried without the comment :D).

Hope not missing something...

**Comment by muarachmann** [comment] 2021-07-28 08:17
> @masterix21
> 
> It's just a fresh Laravel installation with multi tenancy package added.
> 
> https://github.com/aginev/spatie-laravel-multitenancy-test
> 
> Note:
> 
> 1. [App\Multitenancy\Tasks\SwitchTenantDatabaseTask](https://github.com/aginev/spatie-laravel-multitenancy-test/blob/master/app/Multitenancy/Tasks/SwitchTenantDatabaseTask.php) is used when switching tenants because extra database configuration is required. For the sake of the damo all additions are disabled.
> 2. Tenant model has been extended as well just because extra database configuration
> 3. Most the actions are handled at [routes/web.php](https://github.com/aginev/spatie-laravel-multitenancy-test/blob/master/routes/web.php) just for simplicity reasons
> 
> Domain tenant finder has been used. This will require to add some hosts at `/etc/hosts`
> 
> ```
> 127.0.0.1       admin.multitenancy.test
> 127.0.0.1       t1.multitenancy.test
> 127.0.0.1       t2.multitenancy.test
> ```
> 
> Example Nginx config
> 
> ```
> server {
> 	listen 80;
> 	listen [::]:80;
> 
> 	root /home/aginev/Work/playground/multitenancy/public;
> 
> 	index index.php;
> 
> 	server_name admin.multitenancy.test t1.multitenancy.test t2.multitenancy.test;
> 
> 	location / {
> 		try_files $uri $uri/ /index.php?$query_string;
> 	}
> 
> 	# pass PHP scripts to FastCGI server
> 	location ~ \.php$ {
> 		include snippets/fastcgi-php.conf;
> 		fastcgi_pass unix:/var/run/php/php8.0-fpm.sock;
> 	}
> 
> 	# deny access to .htaccess files, if Apache's document root
> 	# concurs with nginx's one
> 	location ~ /\.ht {
> 		deny all;
> 	}
> }
> ```
> 
> Laravel's .env (just the changes from defaults)
> 
> ```
> ...
> APP_URL=http://multitenancy.test
> ...
> DB_CONNECTION=landlord
> ...
> DB_DATABASE=multitenancy
> ...
> ```
> 
> You will need 3 databases (1 landlord and 2 for the tenants) named:
> 
> ```
> multitenancy
> multitenancy-1
> multitenancy-2
> ```
> 
> Run the landlord migrations:
> `php artisan migrate:fresh --database=landlord --path=database/migrations/landlord`
> 
> Visit http://admin.multitenancy.test/ and click at the `Add Tenant` button. A new tenant will be created. Note that 3th click at the button will result a error because the example configuration is made just for 2 tenants. Tenant database will be migrated and 10 dummy users will be added (commands [here](https://github.com/aginev/spatie-laravel-multitenancy-test/tree/master/app/Actions)).
> 
> Visit http://t1.multitenancy.test/. Queued job for random user will be despatched.
> 
> Run `php artisan queue:work --queue=users --once` and will get job failed.
> 
> Run `php artisan queue:retry all` and will get `SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected`
> 
> To be sure that the [SwitchTenantDatabaseTask::makeCurrent](https://github.com/aginev/spatie-laravel-multitenancy-test/blob/33b9e19dea0f4060961e53148a8be00be53c26f8/app/Multitenancy/Tasks/SwitchTenantDatabaseTask.php#L15) has been never called. Added `dd()` statement in there and nothing (of course tried without the comment :D).
> 
> Hope not missing something...

Hi @masterix21 was wondering if you ever got this to work, My jobs are not working either keep getting 
`SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected`

**Comment by masterix21** [comment] 2021-09-23 09:02
@aginev, I can confirm the bug: I'm working to a fix. Thanks.

**Comment by masterix21** [comment] 2021-09-23 09:28
@freekmurze digging in the issue, I found the bug origins.

Using a tenant-aware job with a model tenant-related in the constructor, won't be possible to retry the job if the job fails.

The problem is related to the unserialize method by [Laravel `RetryCommand`](https://github.com/laravel/framework/blob/6216534f14c7cb8bdfa213e5f7e3d357119a4579/src/Illuminate/Queue/Console/RetryCommand.php#L156).

![image](https://user-images.githubusercontent.com/6555012/134482171-42fdefb7-2695-4895-b687-fd1c5e8dd2fa.png)

Unserializing the job instance, there are no events to make a tenant current (and the constructor has a model tenant-related).

We should do a PR in the Laravel framework with an event "FailedJobRehydrating", but I cannot guarantee they will merge it. 

What do you think about it?

**Comment by masterix21** [comment] 2021-09-23 10:08
I found another "fix", but it is ugly.

```php
<?php

namespace App\Jobs;

use App\Models\Tenant;
use App\Models\TenantUser;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Spatie\Multitenancy\Jobs\TenantAware;

class TenantUserJob implements ShouldQueue, TenantAware
{
    use Dispatchable, InteractsWithQueue, Queueable;

    use SerializesModels {
        __unserialize as parent_unserialize;
        __serialize as parent_serialize;
    }

    public function __construct(
        public TenantUser $user
    ) {
      // ...
    }

    public function handle()
    {
        throw new \Exception('Tenant = '. (Tenant::current()?->id ?? "NULL") .' - Multitenancy queue retry test!');
    }

    public function __serialize()
    {
        $values = $this->parent_serialize();

        if (Tenant::checkCurrent()) {
            $values['tenantId'] = Tenant::current()->id;
        }

        return $values;
    }

    public function __unserialize(array $values)
    {
        if (array_key_exists('tenantId', $values) && Tenant::current()?->id !== $values['tenantId']) {
            Tenant::find($values['tenantId'])->makeCurrent();
        }

        $this->parent_unserialize($values);
    }
}

```

![image](https://user-images.githubusercontent.com/6555012/134489532-13862f1b-5eb7-4bcc-93f0-c6694290ce03.png)

**Comment by freekmurze** [comment] 2021-09-29 17:21
@masterix21 Thanks for all your work researching this.

> We should do a PR in the Laravel framework with an event "FailedJobRehydrating", but I cannot guarantee they will merge it.

I would very much prefer that a fix for this would be PRed to Laravel, so we don't have to use our own `SerializesTenantModels`

**Comment by masterix21** [comment] 2021-10-05 18:02
@freekmurze I have released the PR, hoping they will merge it.

**Comment by freekmurze** [comment] 2021-10-06 09:34
Fingers crossed!

**Comment by masterix21** [comment] 2021-10-07 20:31
Merged 🥳

**Comment by masterix21** [comment] 2021-10-15 13:25
I'm closing here due to the PR by @aginev.

**Closed by masterix21** 2021-10-15 13:25 UTC
Labels: bug
