### ISSUE TITLE
Artisan migration commands...

### ISSUE THREAD

**Issue by telkins** [spatie/laravel-multitenancy#152] opened 2020-10-22 15:09 UTC
This is not an issue, rather it's a question: is there value in creating commands that simplify migration?

I'm asking because I have to go to the docs every time I need to migrate.  It would be nice if there are some built-in artisan commands that do this.

At a minimum, I'm thinking it could be something like the following:

- `php artisan tenant:migrate-tenants`: this would, by default, perform the out-of-the-box migration and could eventually allow for various arguments to make it more flexible.
- `php artisan tenant:migrate-landlord`: this would also, by default, perform the out-of-the-box migration and could eventually allow for various arguments to make it more flexible.
- `php artisan tenant:migrate`: this might be a bit more ambitious, but it could perform both the landlord and tenant migrations.

I would like this functionality **and would be willing to submit a PR** should time allow, but wanted to first hear if this is something you guys might consider accepting...assuming it otherwise meets your criteria/standards. 🤓 

Thx.

**Comment by masterix21** [comment] 2020-10-22 15:27
A command to do what you could do already with the native commands. Theoretically, It seems to be like a rat eating its own tail; in practice, instead, it should be useful when you have a lot of tenants.

Please explain your idea better. Thanks.

**Comment by telkins** [comment] 2020-10-22 15:44
Thx, @masterix21.  Thanks for responding so quickly. 👍 

> A command to do what you could do already with the native commands.

I guess I'm not sure what command you're talking about...unless you are talking about the commands described in the documentation (see below).  Can you please confirm or explain?

> in practice, instead, it should be useful when you have a lot of tenants.

Also, could you please clarify what you mean here...?

> Please explain your idea better.

The documentation suggests these two commands to migrate the landlord and tenant databases, respectively:

- `php artisan migrate --path=database/migrations/landlord --database=landlord`
- `php artisan tenants:artisan "migrate --database=tenant"`

I'm suggesting writing the following commands to do the same things:

- `php artisan tenant:migrate-landlord`
- `php artisan tenant:migrate-tenants`

And possibly having a command to do all of it, like so:

- `php artisan tenant:migrate`

Basically, these would be shortcuts or whatever, making it a bit easier for developers...especially for those like me who don't always easily remember the various arguments. 😝 

For me, it would be easier to remember.  If I was unsure, I can just quickly type `art` to see the commands I need to run.  Currently, I have to go to my browser, open a(nother) tab, navigate to the docs, find the right page, scroll to the right spot, then copy/paste/execute. 😱 

I know it may not seem like much, and admittedly it's not a huge time saver, but that's why I'm asking.  😁 

So, hopefully that's a little clearer.  You may be right that it is "[a] command to do what you could do already with the native commands"....but I would change it slightly to say that it is "[a] command to **more easily and quickly** do what you could do already with the native commands." 🤓

**Comment by masterix21** [comment] 2020-10-23 10:12
Sorry, but it would add unneeded complexity. The package philosophy is to be lightweight, and IMHO it would be a duplicate of native "php artisan migrate". Moreover, the migration command could be different project by project.

So, I think it's better to keep all things like already are, at the moment.

Thanks.

**Closed by masterix21** 2020-10-23 10:12 UTC
