### ISSUE TITLE
Applying new sender sending mail on queue 

### ISSUE THREAD

**Issue by alextime** [spatie/laravel-multitenancy#425] opened 2022-12-20 07:39 UTC
Tried on both version 2 and 3 I got issues overriding settings for mail sender on queues, switching tenants.

The queue is tenant aware (queues_are_tenant_aware_by_default config key to true).

I have a couple of fields on tenants table to override mail sender.

I added a new task on switch_tenant_tasks array config to set new mail sender using Laravel Config::set facade when a queue is sending email on the tenant specified on the job.

I checked that tenant_id in jobs table looks always correct, but sometime (not always) emails sent out by Laravel queues are sent using sender details coming from others tenant (not using base config.mail settings)

**Comment by alextime** [comment] 2022-12-20 10:48
I used a class that implements SwitchTenantTask having makeCurrent and forgetCurrent methods that, following [Creating your own task doc](https://spatie.be/docs/laravel-multitenancy/v3/using-tasks-to-prepare-the-environment/creating-your-own-task) overrides config('mail.from.address') on makeCurrent method and restore to default on forgetCurrent method

**Comment by masterix21** [comment] 2023-02-06 23:08
Try with: 

```php
Mail::forgetMailers();
```

Keep us updated. Thanks!

**Comment by masterix21** [comment] 2023-02-09 09:05
@alextime, please give us feedback if your issue is still on the 3.0.2 version. Thanks

**Comment by benddailey** [comment] 2023-03-05 02:48
@alextime Does switching to queue:listen instead of queue:work resolve your problem?

I found this thread while dealing with failed Broadcast and failed laravel-medialibrary conversion jobs. I realized the issue is caused because of the long running worker queue. I ended up on rather simple fix for this issue. Switch production to run worker:listen instead of worker:queue. There is a very small performance penalty for booting the framework for each job but it is better to get the right and proper result than having failed jobs or broadcast messages that don't go anywhere because the have the wrong config parameters.

I switched my supervisor configuration for my worker /etc/supervisor/conf.d/wildcard_auctionit_io-worker.conf as seen below:

```
[program:wildcard_auctionit_io-worker]
process_name=%(program_name)s_%(process_num)02d
#command=/usr/bin/php /var/www/wildcard_auctionit_io/artisan queue:work --sleep 1 --timeout 120
command=/usr/bin/php /var/www/wildcard_auctionit_io/artisan queue:listen --sleep 1 --timeout 120
numprocs=4
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/wildcard_auctionit_io/storage/logs/worker.log
```
Maybe the documentation should be updated to mention running queue:listen instead of queue:work?

**Comment by masterix21** [comment] 2023-06-27 09:24
I'm closing here due to inactivity, but feel free to continue the discussion.

**Closed by masterix21** 2023-06-27 09:24 UTC

**Comment by michaelklopf** [comment] 2026-01-07 11:51
@alextime 

Yo, what did you do at the time?

I have a similar issue. I switch the s3 bucket depending on the tenant. But queueing a job coming from mailgun and setting the tenant with `makeCurrent` doesn't switch the bucket properly.
