### ISSUE TITLE
Eloquent ignores databases when combining tenant and landlord tables in a relationship

### ISSUE THREAD

**Issue by everydaysoftware** [spatie/laravel-multitenancy#429] opened 2023-01-11 08:28 UTC
Problem: 
When **accessing relations defined with tables from landlord and tenant,** eloquent looks up every table in one database **ignoring the UsesLandlordConnection/UsesTenantConnection traits** in the respective Models.

Example:
A tenant.table has a 'hasManyThrough' relationship to a landlord.table over a tenant.through-table ...

`tenant.table-> hasManyThrough(landlord.table::class, tenant.through-table::class)`

resulting in: 

`Base table or view not found: 1146 Table 'landlord.through-table' doesn't exist ...`

Eloquent tries to find the tenant.through-table::class in landlord db even though the UsesTenantConnection trait was defined in the tenant.through-table::class

This not only applies to hasManyThrough relations. 

Workaround: creating views of the needed landlord tables on the tenant db.

Is this a general limitation?

**Comment by masterix21** [comment] 2023-01-11 09:20
Hi @everydaysoftware, please post your code. Thanks

**Comment by everydaysoftware** [comment] 2023-01-11 10:27
Hi @masterix21

thanks for the fast reply. My models look like this: 

```
class BusinessProcess extends Model {
   use UsesTenantConnection;

   public function risks() {
      return $this->hasManyThrough(Risk::class, BusinessProcessRisk::class);
   }
}
```

```
class BusinessProcessRisk extends Model {
   use UsesTenantConnection;
}
```

```
class Risk extends Model {
   use UsesLandlordConnection;
}
```

A BusinessProcess::class has many Risk::class connected via BusinessProcessRisk::class

Accessing the hasManyThrough relation risks() on BusinessProcess::class results in Eloquent looking for the BusinessProcessRisk::class model in the landlord db. 

 It seems that mixing tenant and landlord tables on a relationship is not possible (even though connection traits are applied correctly)

**Comment by denizgolbas** [comment] 2023-01-23 15:19
Can you try declaring to ids in your model method. And capture toSql()

**Comment by masterix21** [comment] 2023-02-06 21:56
It is a Laravel limit. Take a look here: https://github.com/laravel/framework/issues/32171

**Comment by masterix21** [comment] 2023-02-06 22:32
It seems to be the only solution to the issue (but it should be tested well):

```php
class Risk extends Model {
   use UsesLandlordConnection;

    public function getTable(): string
    {
        return $this->getConnection()->getDatabaseName() .'.'. parent::getTable();
    }
}
```

I'm closing here because the issue is unrelated to the package, but feel free to continue the discussion.

**Closed by masterix21** 2023-02-06 22:32 UTC

**Comment by stevethomas** [comment] 2023-06-01 05:38
FWIW there seems to be at least one case where `getTable()` is ignored. 

On pivot tables, when `using()` a custom Pivot model and setting the appropriate connection and prefixing the table name as above, Laravel is going to use the connection inherited from the first model in `belongsToMany`.

This kindof makes sense because Laravel needs to assume that a different connection could mean a totally different database server / engine. 

For example: 
- landlord.users
- tenant.products
- tenant.product_user 

Out of the box, if we try and access `$product->users`, Laravel is going to inherit the connection from the User model (the landlord connection), and try and read from `landlord.product_user`, which doesn't exist. 

To workaround this, provide the second argument of `$this->belongsToMany()`. 

```php
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class Product extends Model
{
    public function users(): BelongsToMany
    {
        return $this->belongsToMany(User::class, $this->getTenantTable('product_user'))
            ->withTimestamps();
    }

    protected function getTenantTable(string $table): string
    {
        return Tenant::current()->database . ".$table";
    }
}
```

I think the other one that breaks is `whereHas` and similar, because it needs to do a sub query to join the tables together, and it pays no attention to the connection defined on the related model. 

In this scenario the `getTable()` example solves this as it seems to actually load the relation and respect the table name.
